spring:
  datasource:    url: jdbc:mysql://localhost:3306/grupo-14-bdd-oo2-2021
    username: root
    password: root12345678
  jpa:
    show-sql: true
    hibernate:      ddl-auto: update
      naming:        strategy: org.hibernate.cfg.ImprovedNaming.Strategy
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect